CREATE TABLE IF NOT EXISTS admin_actions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  service_id UUID NOT NULL REFERENCES services(id) ON DELETE CASCADE,
  action_type TEXT NOT NULL, -- MARK_MILESTONE_PAID | COMPLETE_SERVICE_WITHOUT_FINAL_PAYMENT | REOPEN_SERVICE
  reason TEXT NOT NULL,
  actor TEXT NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


